### ISSUE TITLE
[OSX] Compilation Error - nullptr undeclared

### ISSUE THREAD

**Issue by navv1234** [simulationcraft/simc#2015]
Originally reported on Google Code with ID 2016

```
Trying to compile on Mac with the latest rev gives the following error :
error: use of undeclared identifier 'nullptr'
from qt/util/sc_searchbox.hpp and qt/util/sc_searchbox.cpp introduced in rev 31b4c059b8b4


What version of the product are you using? On what operating system?
Revision a8f12e957e7d   
On Mac OSX 10.8.5 / Qt 5.1.1

```

Reported by `thorvald.termeer` on 2014-02-21 11:13:38
