### PR TITLE
macOS build fix

### LINKED ISSUE #7543: Enable macos nightly build with Qt6.5
I recently tried publishing our nightly builds with the newly released Qt6.5 and hit a blocker with the macos build, see https://github.com/simulationcraft/simc-publish/pull/20

There are errors on macos with `std::filesystem::path`, see https://github.com/simulationcraft/simc-publish/actions/runs/4636357824/jobs/8204171694

```
/Users/runner/work/simc-publish/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qfileinfo.h:99:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemPath() const { return QtPrivate::toFilesystemPath(path()); }
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from ../qt/ImportTab.cpp:7:
In file included from ../qt/sc_AddonImportTab.hpp:8:
In file included from ../qt/util/sc_textedit.hpp:10:
In file included from /Users/runner/work/simc-publish/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QtGui:3:
In file included from /Users/runner/work/simc-publish/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QtGuiDepends:3:
In file included from /Users/runner/work/simc-publish/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QtCore:80:
In file included from ../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdir.h:9:
/Users/runner/work/simc-publish/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qfileinfo.h:100:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemAbsolutePath() const
                     ^
```

If anyone is interested and willing to fix this, please create a pull request for it. I assume that either adjusting some setting (macOS>= 10.15) or adjusting the libc++ version used might fix it, but I personally have no clue about how macos works :-)

fyi @navv1234 @wfarr @philipp-spiess @nuoHep

### PR DESCRIPTION
**Pull request by relalis**
Fixes #7543 building for QT >= 6.

### CODE REVIEW

**Comment by scamille** [comment]
Edit: I didn't correctly follow the issue you linked to. If this seems to resolve QT 6.5 issues, that is great.

File: qt/CMakeLists.txt [hunk 1]
```diff
@@ -30,6 +30,10 @@ if (WIN32)
 endif()
 add_executable(SimulationCraft WIN32 ${source_files})
 
+if (${QT_VERSION_MAJOR} EQUAL 6)
+  set(CMAKE_OSX_DEPLOYMENT_TARGET "10.15")
```
Comment (scamille) [inline qt/CMakeLists.txt:35]:
```suggestion
  # std::filesystem (used indirectly with Qt6.5 on newer compilers) usage requires minimum osx target version of 10.15
  set(CMAKE_OSX_DEPLOYMENT_TARGET "10.15")
```

**Comment by scamille** [comment]
Thanks for finding this out. It might even make sense to unconditionally enable this if we ever start to use std::filesystem in simc itself - but I am bit out of the loop on whether there are plans to upgrade the minimum compilers requirements for that at some point in time or not.

I don't know much about osx version, but going based off some dates from wikipedia about osx 10.15 I just assume that nobody will ever want to run simc with anything older than it. @navv1234 correct me if that is wrong.

File: qt/CMakeLists.txt (hunk 1 above)
Comment (scamille) [reply qt/CMakeLists.txt:35]: This really is just about documenting the `WHY` directly in code. Should also prevent this from easily getting removed again if the purposed is lost.
